# Generated by Django 2.1.3 on 2018-12-13 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181213_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Departamento', verbose_name='Departamento'),
        ),
    ]
